# WINDOW_SIZE = (504, 560)
WINDOW_SIZE = (756, 560)
WINDOW_TITLE = "中国象棋"
CHESS_NAME = []
INIT_COORD = []
UNPLACED_COORD = []
INIT_RANGER = []
UNPLACED_RANGER = []
MIDPOINT = []
MIN_COORD = []
MAX_COORD = []
CHESS_X_Y1 = 2
CHESS_X_Y2 = 22
CHESS_INTERVAL1 = 56
CHESS_INTERVAL2 = CHESS_INTERVAL1 + 1
CHESS_STATE = {}
NAME = []


if __name__ == "__main__":
    pass
